### PR TITLE
Add toHaveStyleRule [React] to README

### PR DESCRIPTION
**Pull request by MicheleBertoli**
@leocreatini this PR adds the new matcher to the README, and changes a bit the output of the expected style.

Without the `[1]`, the style is printed in the following way:
screen shot 2017-05-15 at 21 24 59

For this component:
```js
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`
```

Is it OK or am I doing something wrong?
Thanks!

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Ping @leocreatini :)

**Comment by leocreatini** [comment]
@MicheleBertoli: Hey, checking right now!

**Comment by leocreatini** [comment]
Yes, it seems that it only works with `[1]`. Not sure what happened but this looks good to me.

**Comment by MicheleBertoli** [comment]
Perfect, thank you very much @leocreatini.

**Pull request merged**
