### PR TITLE
Extend global namespace with jest matcher

### PR DESCRIPTION
**Pull request by tobilen**
fixes https://github.com/styled-components/jest-styled-components/issues/291

### CODE REVIEW

**Comment by tobilen** [comment]
published in `@invisionag/jest-styled-components`@7.0.1 for testing purposes

**Comment by tobilen** [comment]
@probablyup anything missing?

**Comment by landisdesign** [comment]
Also fixes #298

**Comment by bdelaforest** [comment]
@probablyup Is there something blocking this PR?  It would be great if you could have a look.
Without this we can't update styled-components to v5 :(

**Comment by tobilen** [comment]
@bdelaforest you can use the published fork: https://github.com/styled-components/jest-styled-components/pull/308#issuecomment-595184516

i'll deprecate it as soon as it is no longer needed, so you'll get a reminder to switch back

**Comment by tobilen** [comment]
@probablyup are we getting a release for this patch?

**Comment by probablyup** [comment]
Waiting for the last open PR to be finalized


On March 24, 2020 at 5:30:41 PM, Tobias Lengsholz (notifications@github.com)
wrote:

@probablyup <https://github.com/probablyup> are we getting a release for
this patch?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/styled-components/jest-styled-components/pull/308#issuecomment-603515329>,
or unsubscribe

**Pull request merged**
