### PR TITLE
Pseudo selectors support

### PR DESCRIPTION
**Pull request by yanawaro**
@MicheleBertoli I manage to get it done with your help for the hasClassNames function. Thanks 😃 
- When getting rules, it needs to distinguish whether the options includes a At rule or not. I added a ```hasAtRule``` function for checking (Not known if this should be in utils.js?). The array containing at rules value should be easily added for checking, but right now can we just keep it simple? (I think most users would be using media rules. 😂 )
- Letting the user to pass colon symbols in the pseudo option makes it dynamically for users that like single, or double colons.
- Now, we can accomplish combinations At rules and pseudo selectors. 👍 
- I have to take back the option default as empty object as undefined will break at ```hasAtRule``` function

### CODE REVIEW

**Comment by lyuzashi** [comment]
I was looking for this feature mere hours before this pull request and I've been testing it out. Works great! Thank you @yanawaro! +1 for getting this merged in

**Comment by MicheleBertoli** [comment]
This is AWESOME, thanks @yanawaro.
I love the way you approach problems, and your solutions are always simple and effective.

There's is only one thing I was wondering before merging.
It's a great idea to let the users specify their own modifiers (eg. `:` VS `::`) but this means it doesn't necessarily have to be a pseudo class.
For example, your code works with attributes (e.g. `[myAttr]`) as well.
Should we limit the option to pseudo, or should we call it "modifier" (or something)?
What do you think?

Also, thanks @lyuzashi for testing it out.

**Comment by yanawaro** [comment]
@MicheleBertoli You're right! I was just too focused on just pseudo selectors. Forgot about selecting with attributes is the same way. Yep, it could be called "modifier" to align things up with the repo [https://github.com/mbasso/styled-components-test-utils](styled-components-test-utils). 👍 

Yes, I also like this repo code style. It's looks minimal, clean and effective. And I like to follow and not mess things up. 😂 

I'll submit changes with some more tests for attributes selectors.

**Comment by MicheleBertoli** [comment]
Perfect @yanawaro.
I'll merge this and publish a new version very soon.
Thank you very much!

**Pull request merged**
