### PR TITLE
Add toHaveStyleRule for native platform

### PR DESCRIPTION
**Pull request by Kureev**
Literally, merging https://github.com/Kureev/jest-styled-components-matcher in. 

Please, let me know if something.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Hello @Kureev, thanks for the PR - it's awesome!

I just have a few thoughts/comments:

- I'm not sure if we should separate the functionalities between web and native. 
Hopefully, we will be able to make them work on both platforms.
At the moment, we could just put a label next to the function name in the README (e.g. [native]).

- The `jest-matcher-utils` package should be already present in the test environment, so I would suggest you to add it to the `peerDependencies` section.

- I guess the README has to be completely reorganised in term of screenshots/snippets, so that we can make it look more consistent.
If you prefer, just push the code and then I'll work on it later.

What do you think?

**Comment by Kureev** [comment]
Sounds great! I will move `jest-matcher-utils` to the `peerDependencies` section and leave README.md up to you, if you don't mind :)

**Comment by Kureev** [comment]
I just tried to move `jest-matcher-utils` to `peerDependencies`, but it seems it doesn't work:

```
 FAIL  app/components/foundation/Avatar.spec.js
  ● Test suite failed to run

    Cannot find module 'jest-matcher-utils' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (../jest-styled-components-matcher/index.js:5:1)
```

**Comment by MicheleBertoli** [comment]
Oh, that's weird @Kureev.
The package should be automatically installed with Jest 19+.

If I run:
```bash
rm -rf node_modules && yarn install
ls node_modules | grep jest-matcher-utils
```
I can see it.

**Comment by Kureev** [comment]
Should I revert changes in README.md?

**Comment by MicheleBertoli** [comment]
Yes, please.
I'll work on the README once this is merged.
I'll ask you to review it when it's done if you don't mind.
Thanks!

**Comment by Kureev** [comment]
Done

**Comment by MicheleBertoli** [comment]
Hello @Kureev, I just wanted to tell that I didn't forget about this :)
I've just been a little bit busy in the last few days, but I'm going to merge this and write the README as soon as possible.

**Comment by Kureev** [comment]
Thanks for an update, @MicheleBertoli!

No problem, I'm not hurry with this one.

**Comment by Kureev** [comment]
Thanks, @MicheleBertoli! Let me know if I can help with something else ❤️

**Pull request merged**
