### PR TITLE
Add new native tests

### PR DESCRIPTION
**Pull request by Kureev**
Hi @MicheleBertoli!

As I promised, I added (just adapted existing ones tbh) a few new `toHaveStyleRule`-related tests. Thanks to these tests, I found out that some functionality like regexp matching, expecting null and some style name mismatching (`background` translates to `backgroundColor` in React Native) is not covered in the code. I'll follow up on this in the following PRs. At least, now we know that the issue exists. I disabled failing tests and will re-enable them once missing functionality is there.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
WOW, this is awesome!
Thank you very much, @Kureev.
I love when tests make it easier to find the edge cases.

If you agree, I would just disable the `message when property not found` test before merging because we are storing the wrong error in the snippet.

**Comment by MicheleBertoli** [comment]
Ping @Kureev 
You might have missed my last comment :)

**Comment by Kureev** [comment]
Oh, indeed I missed it (was on vacation). Sure thing, feel free to adjust PR according to your preferences 😉

**Comment by MicheleBertoli** [comment]
Perfect, thank you very much @Kureev.
I hope you enjoyed your vacation, and see you soon : )

**Pull request merged**
