### PR TITLE
Fix type error with `modifier`

### LINKED ISSUE #268: Type error with `modifier`?
Tested on both v6 latest and v7 beta.

The docs show this example:

```typescript
test('nested buttons are flexed', () => {
  const tree = renderer.create(<ButtonList><Button /></ButtonList>).toJSON()
  expect(tree).toHaveStyleRule('flex', '1 0 auto', {
    modifier: css`${Button}`,
  })
})
```

However, when using Typescript, we get the following error: `Type 'FlattenSimpleInterpolation' is not assignable to type 'string'.`

Seems like a simple enough fix that I can tackle if needed (change interface for `modifier`), but just wanted to make sure that the docs actually describe accurate + intended behavior before I start diving into this. Thanks!

### PR DESCRIPTION
**Pull request by timhwang21**
Closes #268.

### CODE REVIEW

**Review by cscheffauer — APPROVED** [review]
Looks solid to me!

**Review by MateusGruber — APPROVED** [review]

**Comment by probablyup** [comment]
Why are you trying to put a tagged template literal into the `modifier` field?

**Comment by timhwang21** [comment]
Because that's what the README suggests for this use case. 

> If a rule is nested within another styled-component, the `modifier` option can be used with the [`css`](https://www.styled-components.com/docs/api#css) helper to target the nested rule.

```js
const Button = styled.button`
  color: red;
`

const ButtonList = styled.div`
  display: flex;

  ${Button} {
    flex: 1 0 auto;
  }
`

import { css } from 'styled-components';

test('nested buttons are flexed', () => {
  const tree = renderer.create(<ButtonList><Button /></ButtonList>).toJSON()
  expect(tree).toHaveStyleRule('flex', '1 0 auto', {
    modifier: css`${Button}`,
  })
})
```

**Comment by probablyup** [comment]
@timhwang21 ok cool, could you merge from `main` and run `yarn` to clear the lockfile merge conflict?

**Comment by timhwang21** [comment]
Will do -- looks like `@types/styled-components` has been updated since then so I updated that to latest as well.

**Review by probablyup — APPROVED** [review]

**Pull request merged**
