### PR TITLE
Support styled-components v2

### PR DESCRIPTION
**Pull request by MicheleBertoli**
Feedback is welcome

### CODE REVIEW

**Comment by ismay** [comment]
I've tried this branch with `yarn link` but I'm getting:

```
TypeError: Cannot read property '1' of null

      at Object.it (src/shared/components/container/components/Container.test.jsx:9:21)
```

for this test:

```
import 'jest-styled-components'
import React from 'react'
import { shallow } from 'enzyme'
import Container from './Container'

describe('<Container />', () => {
  it('renders correctly', () => {
    const wrapper = shallow(<Container />)
    expect(wrapper).toMatchStyledComponentsSnapshot()
  })
})
```

I assume I'm doing something wrong here?

**Comment by MicheleBertoli** [comment]
Ops @ismay, thanks for your comment.
Just to make sure: are you using Styled Components `2.0.0-17` in your project?
Also, if you checkout this branch and run `yarn test`, do tests pass?

**Comment by ismay** [comment]
Yep, I'm using `2.0.0-17` and locally both jest-styled-components tests pass (for the `styled-components-v2` branch). The steps to reproduce are:

* clone && `git checkout styled-components-v2`
* `yarn`
* `yarn link`
* cd to other repo && `yarn link jest-styled-components`
* add `"testEnvironment": "node"` to jest config
* add `import 'jest-styled-components'` and replace `toMatchSnapshot` with `toMatchStyledComponentsSnapshot`
* results in the error above

See also https://github.com/ismay/ismaywolff.nl/pull/404 for the changes I made

**Comment by ismay** [comment]
Maybe the problem is because of the `yarn link`. I could test it for you with an actual npm install if you release this on npm as an alpha version (if there aren't any other things that could explain this error).

**Comment by MicheleBertoli** [comment]
I can confirm that the problem is related to `yarn link`, please try `yarn add jest-styled-components@next`.
Thank you very much @ismay.

**Comment by ismay** [comment]
Works: https://travis-ci.org/ismay/ismaywolff.nl/builds/229659187#L464! 🎉 🎉 🎉 

By the way, a lot of my other tests are now failing because of the `"testEnvironment": "node"`. [Jest-glamor-react](https://github.com/kentcdodds/jest-glamor-react) seems to not need the testenv to be set to `node`, would a similar solution be possible for this lib as well? But that's just an aside.

**Comment by MicheleBertoli** [comment]
🙌 Yay, I'm happy to hear that!
Thanks for your help.

I agree that setting the `testEnvironment` to `node` isn't optional, but Jest v20 [introduces](https://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html#new-improved-testing-apis) a new annotation which lets you specify the env [on a single file](https://github.com/styled-components/jest-styled-components/blob/master/test/index.spec.js#L1).
Also, I didn't have time to check the internals of the Styled Components yet but my goal is finding a solution to that.

**Comment by ismay** [comment]
Happy to help. Thanks for creating this, it's gonna be nice to try it out!

> I agree that setting the testEnvironment to node isn't optional, but Jest v20 introduces a new annotation which lets you specify the env on a single file.

Ah yeah, that should already fix what I'm running into I think, thanks!

**Comment by MicheleBertoli** [comment]
Thank you very much @philpl

**Comment by SimonDegraeve** [comment]
Using styled-components 3.0.0, I have got the following error as soon as I import the module in my test files (tested with jest 19 and 20)

```js
BrowserTag cannot be cloned!
      
      at Object.<anonymous>.it (src/components/layout/hero.test.js:281:16)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by MicheleBertoli** [comment]
v3? That escalated quickly :)

I assume it's v2 and the error looks like you missed the `testEnvironment` configuration.
Please check the README or my comment [here](https://github.com/styled-components/jest-styled-components/pull/14#issuecomment-299708427), and let us know if it works.

**Comment by SimonDegraeve** [comment]
The `testEnvironment` is set to `node`. 

This is really v3. From `npm info`:
```js
{ modified: '2017-05-07T12:24:01.123Z',
     created: '2017-03-18T12:57:21.184Z',
     '0.0.0': '2017-03-18T12:57:21.184Z',
     '0.1.0': '2017-03-18T13:09:59.044Z',
     '0.1.1': '2017-03-18T13:13:47.698Z',
     '1.0.0': '2017-03-19T21:26:14.180Z',
     '1.1.0': '2017-03-23T21:48:22.377Z',
     '1.1.1': '2017-03-23T22:54:43.286Z',
     '1.2.0': '2017-03-24T21:40:44.679Z',
     '1.3.0': '2017-03-24T22:23:18.871Z',
     '1.3.1': '2017-03-26T09:01:41.828Z',
     '1.3.2': '2017-03-26T10:33:36.394Z',
     '1.3.3': '2017-04-16T21:28:06.394Z',
     '2.0.0': '2017-05-01T09:42:20.219Z',
     '3.0.0-0': '2017-05-07T12:24:01.123Z' }
```

I get this error now:
```js
TypeError: styleSheet.rules is not a function
```

**Comment by ismay** [comment]
I think you mean this library's version. Styled components doesn't have a v3.

**Comment by MicheleBertoli** [comment]
Oh, I see `jest-styled-components` v3 :)
That's weird, the error looks really like the `testEnvironment` is somehow not correct.
Which version of `styled-components` are you using?

Also, did you try cloning this branch, running `yarn test` and see if it works?

**Comment by SimonDegraeve** [comment]
Indeed I meant `jest-styled-components`. Sorry about that.

So I tried this branch and all the tests are passing. I use `styled-omponents@2.0.0-17`.

**Comment by SimonDegraeve** [comment]
So it is working now, I had to manually specify `@jest-environment node` at the top of my test file. Even if it is already specified inside the `package.json`.

**Comment by ismay** [comment]
To anyone looking for an example implementation with jest 20, styled-components v2 and this branch of jest-styled-components, this is how I did it: https://github.com/ismay/ismaywolff.nl/pull/414

It works wonderfully! Thanks @MicheleBertoli !

**Comment by Thr44** [comment]
Thanks @MicheleBertoli ! @ismay your example code was great to get it going!

I Updated a vast set of tests, and all are working wonderfully except one case that I narrowed down to this test:

`/**
* @jest-environment node
*/
import 'jest-styled-components';

import React from 'react';
import renderer from 'react-test-renderer';

describe('Broken Component Tests', () => {

  it('should render a basic div', () => {
    const container = renderer.create(
      <div></div>
    );
    expect(container).toMatchSnapshot();
  });

});`

If I comment the import "jest-styled-components" the test passes. Otherwise it throws an error:
  ● Broken Component Tests › should render a basic div

    TypeError: Cannot read property '1' of null

      at Object.<anonymous> (src/js/shared/react/broken.test.js:15:23)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  Broken Component Tests
    ✕ should render a basic div (3ms)

can anyone repro or have a solution?

**Comment by ismay** [comment]
By the way @MicheleBertoli , the `styled-components` peer-dependency for this branch is still at version 1. I'm getting warnings when installing that it doesn't match.

**Comment by MicheleBertoli** [comment]
Thanks @Thr44 @ismay, fixed both issues :)

**Comment by xDae** [comment]
what is the status of this PR?

**Comment by MicheleBertoli** [comment]
Thanks @xDae, this branch works with the Styled Components v2.
I'm just waiting before merging that the v2 is officially announced, and there are no changes to the APIs.
You can use this by running: `yarn add jest-styled-components@next`.
Please let me know if you find any issue.

**Comment by mxstbr** [comment]
We're almost ready to release, it'll happen sometime this week!

**Comment by MicheleBertoli** [comment]
Whoa @mxstbr, I can't wait for that!
Thanks for the update.

**Comment by simobasso** [comment]
I have tried `jest-styled-components@next` and doesn't works :(.

```
...
    "styled-components": "^2.0.0",
...
    "jest": "^20.0.4",
    "jest-styled-components": "next",
    "jsdom": "^11.0.0",
...
```

this test works on `jest-styled-components@2.1.1`:
```
 FAIL  components/Header/tests/index.test.js (7.263s)
  ● <H1 /> › should render its css

    BrowserTag cannot be cloned!

      at Object.<anonymous> (app/components/Header/tests/index.test.js:28:31)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

on this component:

```
export const HiddenH1 = styled.h1`
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
`;
```

with this test

```
/**
 * @jest-environment node
 */
// ...
 it('should render its css', () => {
    const renderedComponent = shallow(<H1 />);
    expect(renderedComponent).toMatchStyledComponentsSnapshot();
  });
// ...
```

I'm use `jsdom` to mount component with this `setupTestFrameworkScriptFile`.

```
import { JSDOM } from 'jsdom';

const dom = new JSDOM('');
global.document = dom.window.document;
global.window = dom.window;
```

also I've set `"testEnvironment": "node"` in my package.json

The ServerStyleSheet's [constructor](https://github.com/styled-components/styled-components/blob/master/src/models/ServerStyleSheet.js#L87) use the [BrowserStyleSheet](https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L146) when `document` is defined.

**Comment by MicheleBertoli** [comment]
Hello @simobasso, thanks for your comment.
What's the use case of setting up `jsdom` manually? 
With Jest you don't actually need to load `jsdom` in your `setupTestFrameworkScriptFile` (Jest does it for you), and I think your setup conflicts with the `testEnvironment` setting.

**Comment by MicheleBertoli** [comment]
Shapshots work with v2, we are almost ready to go :)
@Kureev @leocreatini can you please make sure the matchers work with `styled-components` v2 as well? Also, could you add some tests?
Thanks!

**Comment by luftywiranda13** [comment]
I can confirm that `toMatchStyledComponentsSnapshot()` is working find in the latest CRA (v1.0.6)..
also with if rendered using enzyme's shallow()

**Comment by MicheleBertoli** [comment]
Perfect, thank you very much @luftywiranda13.

**Comment by luftywiranda13** [comment]
@MicheleBertoli 
screen shot 2017-05-26 at 12 34 13

but I got error when using `toMatchStyleRule()`.. already set jest environment to node

**Comment by MicheleBertoli** [comment]
Exactly @luftywiranda13, I'm experiencing the same issue.
That's why I [asked](https://github.com/styled-components/jest-styled-components/pull/14#issuecomment-304191504) @leocreatini (who knows the matcher better) to look into it.
Let's wait for him to give us an update.
Thanks!

**Comment by simobasso** [comment]
@MicheleBertoli thanks for your fast reply.

I've resolved using `jest-environment jsdom` only where I need to use mount API or DOM manipulation.

Thanks

**Comment by leocreatini** [comment]
Hey @MicheleBertoli, I am traveling/vacationing until Sunday. I'll do my best to check the problem as soon as possible. Also not using my regular laptop, so I apologize if it takes longer than expected.

**Comment by MicheleBertoli** [comment]
@leocreatini Please enjoy your trip and forget about this repo :)

**Comment by newswim** [comment]
Just wanted to chime in, after wrestling with configuration and upgrades for a few hours, it's all working. Funny enough, `toMatchStyledComponentsSnapshot` seems to work whether using node or jsdom jest environments. Also it's working with both `renderer` and `shallow` from Enzyme. 🍾

**Comment by MicheleBertoli** [comment]
Thanks for trying this version of the package @newswim.
I can confirm it works with both `test-renderer` and `enzyme` (see [tests](https://github.com/styled-components/jest-styled-components/blob/styled-components-v2/test/index.spec.js)).
However, if you don't set the right node environment, it throws:
>  BrowserTag cannot be cloned!

**Comment by newswim** [comment]
@MicheleBertoli this is true, that's a distinction left up to the particular test file and dependencies of the component. For the time being, it's not an impediment to add a tag to _some_ files,

```js
/**
 * @jest-environment node
 */
```

however, it's probably reasonable to think that `jsdom` should be the default. A few of the components I've tested require it.

**Comment by tino-junge** [comment]
Hi @MicheleBertoli, thanks for this PR. Any plans when this will get merged?

**Comment by MicheleBertoli** [comment]
Hello @tino-junge, thank you very much!

Before merging this we need to fix the `toHaveStyleRule` matcher for React, which doesn't seem to work with the final version of `styled -components` v2.
I was waiting for @leocreatini who is the original contributor for that matcher because I'm super busy atm, but any other contribution (cc @George-Payne) is more than welcome :)))

However, you can install this version now (if you only use the snapshots): `yarn add --dev jest-styled-components@next`.

**Pull request merged**
