### PR TITLE
Fix #355 - Diff showing on unchanged snapshot lines

### LINKED ISSUE #355: Diff showing on unchanged snapshot lines
There is an issue with diff output from jest when changes are found in snapshots. Specifically, it will show extraneous diffs in lines that have no changes:

```diff
  .c0 > span {
-   margin-left: 0;
-   margin-right: 0;
+   margin-left: 0;
+   margin-right: 0;
  }
```

The detection of changes itself is not flawed. This diff issue only happens when legitimate changes are detected elsewhere in the snapshot. The issue resides in the logic printing the changes. 

Another CSS-in-JS library, emotion, and its jest library, @emotion/jest, had a very similar issue with diff output. It was identified in https://github.com/emotion-js/emotion/issues/1847 and resolved with a serializer overhaul in https://github.com/emotion-js/emotion/pull/1850 .

The root cause of the issue starts with some behavior introduced with Jest v25. Prior to Jest v25, snapshot diffs printed to stdout were sensitive to indentation, but a [pull request](https://github.com/facebook/jest/pull/9203) made it insensitive to indentation like so: indent diff before-after

However, this new diff logic requires that snapshot serializers respect the indentation config in order for it to work properly. Older serializers that don't take the indentation config into account can get false positives on changed lines (like the diff I shared above). There is actually a [fallback in the jest-snapshot logic to account for this](https://github.com/facebook/jest/blob/615084195ae1ae61ddd56162c62bbdda17587569/packages/jest-snapshot/src/printSnapshot.ts#L318-L321), but in the case of jest-styled-components and presumably @emotion/jest, there is a [mixture of compliant serializers and non-compliant serializers called to produce the output](https://github.com/styled-components/jest-styled-components/blob/5448282e46b1a373a3b87f6ad10ea1541cdefec5/src/styleSheetSerializer.js#L128-L130), which results in the fallback failing to work correctly.

The fix for this issue must be made in the logic provided by jest-styled-components.

First, the serializer must be updated from the old plugin style (`{ test(){}, print(){} }`) to the new plugin style (`{ test(){}, serialize(){} }`), in order to receive indentation configuration in the arguments. This may lose support for very old versions of Jest (I have confirmed at least [`jest >= 22.0.0` would be fine](https://jestjs.io/docs/en/22.x/configuration#snapshotserializers-arraystring)), so it might need to be considered a breaking change if the jest version is not enforced somewhere (I didn't see it in peerDependencies). Following that change, we have two options to fix the diff issue:

1. Respect the indentation configuration provided by jest. This is made difficult by the dependency on the `css` library for the serialization of style rules. That library has yet-unfixed bug in that [indentation set as an empty string is ignored](https://github.com/reworkcss/css/pull/151).

2. Modify the indentation config being passed on by the serializer in jest-styled-components such that all serializers it calls are equally ignorant to indentation configuration, helping the fallback in jest-snapshot be triggered. This would allow us to fix the issue just with changes in this library, but it has the potential to change users' existing snapshots if they were using custom indentation before, and therefore might be considered a breaking change.

### PR DESCRIPTION
**Pull request by fritz-c**
This PR is designed to fix #355 

I am keeping this as a draft PR until the merging and release of https://github.com/reworkcss/css/pull/151 , which is required for the fix to work.

### CODE REVIEW

**Comment by probablyup** [comment]
@fritz-c unfortunately it doesn't seem like this is working with latest code. I'm interested in landing the change though if you can get it working again

**Comment by fritz-c** [comment]
@probablyup Unfortunately, while the branch with the fix in `css` did get merged, it has not been released as a new npm version. Afraid this fix is stalled until that happens, unless you could live with setting the `css` dependency version to the commit with the fix, or releasing your own npm package based on the current master branch.

**Comment by probablyup** [comment]
I'm fine with that. Or if the code is small enough and the license allows we can just inline it.

**Comment by cincodenada** [comment]
Ha, I just made this same journey and had prepared basically the exact same fix. I put in a good word at `css`, and also found out there's also a fork at https://github.com/adobe/css-tools that integrates this fix, but it's a rewrite in TS and hasn't had a release yet. I've opened an issue there asking if they would be willing to do an interim 3.0.1 release in the meantime at their fork.

If we don't see movement on either of those soon, I think it's worth doing one of the other solutions above, or using something like [patch-package](https://www.npmjs.com/package/patch-package) to apply the change, it's a two-line patch.

Heck, you might even be able to monkeypatch if you want to get messy about it. It ain't pretty, but this fixed it for me - the class being patched is instantiated when `serialize()` is called, so it should be robust to ordering concerns even:
```
require('css/lib/stringify/identity').prototype.indent = function(level) {
  this.level = this.level || 1;

  if (null != level) {
    this.level += level;
    return '';
  }

  return Array(this.level).join(typeof this.indentation == 'string' ? this.indentation : '  ');
};
```

**Comment by holblin** [comment]
Do you think this will fix the issue? https://github.com/styled-components/jest-styled-components/pull/416

**Comment by cincodenada** [comment]
> Do you think this will fix the issue? #416

Indeed it should! I somehow missed that the fork already had a release available, since it is I think that is the best option here. I'll double-check on Monday when I have my code at hand, but the fix does appear to be in 4.0, so that should fix the issue. Thanks for maintaining your fork, @holblin!

**Comment by probablyup** [comment]
@fritz-c could you rebase and get this mergeable? Thanks!

**Pull request closed without merging**
